#!/bin/bash

# Base
sudo dnf install -y \
    tailscale \
    zsh \
    btop \
    vim \
    nvim \
    ranger \
    fastfetch

# Desktop
sudo dnf install -y \
    adw-gtk3-theme \
    source-foundry-hack-fonts \
    syncthing \
    thunderbird \
    xournalpp \
    mpv \
    celluloid \
    zathura

# Utilities
sudo dnf install -y \
    gh \
    pipx \
    speedtest-cli

# Filesystem
sudo dnf install -y \
    btrfs-assistant \
    deja-dup \
    ecryptfs-utils

# Optional
# sudo dnf install -y \
#     texlive-scheme-medium
